### ISSUE TITLE
Temporary change theme for Webmention request

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-uf2#38]
What about bundling a microformatted default barebone theme (no style, just POSH) and use this theme if the request useragent is `/.*webmention.*/`?

**Comment by dshanske** [comment]
Does everyone use this in their user agent?

**Comment by pfefferle** [comment]
From the spec:

> Senders may customize the HTTP User Agent [RFC7231] used when fetching the target URL in order to indicate to the recipient that this request is made as part of Webmention discovery. In this case, it is recommended to include the string "Webmention" in the User Agent. This provides people with a pointer to find out why the discovery request was made.

**Comment by pfefferle** [comment]
@aaronok @indieweb/wordpress what do you think?

**Comment by snarfed** [comment]
hrm, i'm not sure. sounds like this would have most of the problems we've documented in https://indieweb.org/sidefile-antipattern . i imagine you'll end up with different content in this special theme, and that will diverge from the user-visible theme even more over time. not to mention you then have twice the maintenance work since there are two themes instead of one.

**Comment by aaronpk** [comment]
Sounds kind of like doing content negotiation to return a different document for a specific request. I'm not a huge fan of requiring content negotiation but it seems that would be a better approach than this theme switching, since at least there are existing defined behaviors for it. Theme switching seems like it'd be full of problems like if there is a cache plugin or if it's behind a caching cdn...

**Comment by pfefferle** [comment]
@aaronpk for example a jf2 feed as fallback if theme does not support mf2?

Like: `Accept: text/html, application/jf2feed+json`

**Comment by aaronpk** [comment]
Yeah exactly, that way the client can tell the server what formats it can handle, so the server can decide to return a jf2feed (or maybe just the microformats json?) instead. This should also work behind caching proxies since they should take the Accept header into account.

Just to be clear, I'm not sold on this idea to begin with, but I would hate to see a super non-standard way of doing it.

**Comment by pfefferle** [comment]
I already started an experimental plugin over a year ago https://github.com/pfefferle/wordpress-uf2-feed

But I got your point, perhaps we can start a brainstorming page in the wiki...

**Comment by pfefferle** [comment]
* Further discussions: https://chat.indieweb.org/dev/2018-07-29#t1532903257177900
* The Wiki Page: https://indieweb.org/rel-alternate
* A first draft implementation: https://github.com/indieweb/wordpress-mf2-feed
